![car](car.jpg)

Insurance companies invest a lot of [time and money](https://www.accenture.com/_acnmedia/pdf-84/accenture-machine-leaning-insurance.pdf) into optimizing their pricing and accurately estimating the likelihood that customers will make a claim. In many countries insurance it is a legal requirement to have car insurance in order to drive a vehicle on public roads, so the market is very large!

Knowing all of this, On the Road car insurance have requested your services in building a model to predict whether a customer will make a claim on their insurance during the policy period. As they have very little expertise and infrastructure for deploying and monitoring machine learning models, they've asked you to identify the single feature that results in the best performing model, as measured by accuracy, so they can start with a simple model in production.

They have supplied you with their customer data as a csv file called `car_insurance.csv`, along with a table detailing the column names and descriptions below.



## The dataset

| Column | Description |
|--------|-------------|
| `id` | Unique client identifier |
| `age` | Client's age: <br> <ul><li>`0`: 16-15</li><li>`1`: 26-39</li><li>`2`: 40-64</li><li>`3`: 65+</li></ul> |
| `gender` | Client's gender: <br> <ul><li>`0`: Female</li><li>`1`: Male</li></ul> |
| `driving_experience` | Years the client has been driving: <br> <ul><li>`0`: 0-9</li><li>`1`: 10-19</li><li>`2`: 20-29</li><li>`3`: 30+</li></ul> |
| `education` | Client's level of education: <br> <ul><li>`0`: No education</li><li>`1`: High school</li><li>`2`: University</li></ul> |
| `income` | Client's income level: <br> <ul><li>`0`: Poverty</li><li>`1`: Working class</li><li>`2`: Middle class</li><li>`3`: Upper class</li></ul> |
| `credit_score` | Client's credit score (between zero and one) |
| `vehicle_ownership` | Client's vehicle ownership status: <br><ul><li>`0`: Does not own their vehilce (paying off finance)</li><li>`1`: Owns their vehicle</li></ul> |
| `vehcile_year` | Year of vehicle registration: <br><ul><li>`0`: Before 2015</li><li>`1`: 2015 or later</li></ul> |
| `married` | Client's marital status: <br><ul><li>`0`: Not married</li><li>`1`: Married</li></ul> |
| `children` | Client's number of children |
| `postal_code` | Client's postal code | 
| `annual_mileage` | Number of miles driven by the client each year |
| `vehicle_type` | Type of car: <br> <ul><li>`0`: Sedan</li><li>`1`: Sports car</li></ul> |
| `speeding_violations` | Total number of speeding violations received by the client | 
| `duis` | Number of times the client has been caught driving under the influence of alcohol |
| `past_accidents` | Total number of previous accidents the client has been involved in |
| `outcome` | Whether the client made a claim on their car insurance (response variable): <br><ul><li>`0`: No claim</li><li>`1`: Made a claim</li></ul> |

In [2]:
# Import required modules
import pandas as pd
import numpy as np
from statsmodels.formula.api import logit

# Start coding!
data = pd.read_csv('car_insurance.csv')
data = data[data.isna().any(axis=1)]
data['annual_mileage'] = data['annual_mileage'].fillna(data['annual_mileage'].mean()).round(0)
data['credit_score'] = data['credit_score'].fillna(data['credit_score'].mean())

#Preparing for modeling
models = []
features = data.drop(columns=['outcome', 'id']).columns

for model in features:
    x = logit(f"outcome ~ {model}", data=data).fit()
    models.append(x)

    
accuracies = []

for i in range(0, len(models)):
    conf_matrix = models[i].pred_table()
    TN = conf_matrix[0,0]
    TP = conf_matrix[1,1]
    FN = conf_matrix[1,0]
    FP = conf_matrix[0,1]
    accuracy = (TN + TP) / (TN + TP + FN + FP)
    accuracies.append(accuracy)
    i=+1
print(accuracies)
best_model = accuracies.index(max(accuracies))
best_feature = features[2]
best_accuracy = max(accuracies)

best_feature_df = pd.DataFrame({'best_feature': best_feature, 'best_accuracy': best_accuracy}, index=[0])

print(best_feature_df)
data.head(30)

Optimization terminated successfully.
         Current function value: 0.507682
         Iterations 6
Optimization terminated successfully.
         Current function value: 0.618213
         Iterations 5
Optimization terminated successfully.
         Current function value: 0.468290
         Iterations 8
Optimization terminated successfully.
         Current function value: 0.605005
         Iterations 5
Optimization terminated successfully.
         Current function value: 0.522906
         Iterations 6
Optimization terminated successfully.
         Current function value: 0.596356
         Iterations 5
Optimization terminated successfully.
         Current function value: 0.570273
         Iterations 5
Optimization terminated successfully.
         Current function value: 0.572413
         Iterations 6
Optimization terminated successfully.
         Current function value: 0.582219
         Iterations 5
Optimization terminated successfully.
         Current function value: 0.599827
         Iterations 5
Optimization terminated successfully.
         Current function value: 0.624446
         Iterations 5
Optimization terminated successfully.
         Current function value: 0.618325
         Iterations 5
Optimization terminated successfully.
         Current function value: 0.628605
         Iterations 4
Optimization terminated successfully.
         Current function value: 0.568438
         Iterations 7
Optimization terminated successfully.
         Current function value: 0.607005
         Iterations 6
Optimization terminated successfully.
         Current function value: 0.561519
         Iterations 7
[0.7774176121015667, 0.6774716369529984, 0.7725553754727175, 0.6801728795245813, 0.7536466774716369, 0.6947595894111291, 0.7169097784981091, 0.6774716369529984, 0.6774716369529984, 0.6774716369529984, 0.6774716369529984, 0.6796326310102647, 0.6774716369529984, 0.6774716369529984, 0.6774716369529984, 0.6774716369529984]
         best_feature  best_accuracy
0  driving_experience       0.777418

         id  age  gender  ... duis past_accidents outcome
13   569640    0       0  ...    0              0     0.0
15   906223    1       0  ...    0              0     0.0
16   517747    3       1  ...    2              1     0.0
17    24851    0       1  ...    0              0     1.0
18   104086    1       0  ...    0              0     1.0
23      217    0       1  ...    0              0     0.0
37   511757    2       0  ...    0              1     0.0
38   429947    3       1  ...    0              5     0.0
47   921097    2       0  ...    0              2     0.0
55   437535    1       0  ...    0              0     0.0
58   123941    2       0  ...    0              0     0.0
61   171578    1       1  ...    0              1     0.0
64   788111    2       0  ...    0              1     0.0
65   407453    2       0  ...    0              0     0.0
72   422816    2       1  ...    0              7     0.0
73   307408    1       0  ...    0              0     0.0
92   509815    1       0  ...    0              0     0.0
99    55670    1       1  ...    1              0     0.0
101  814196    0       0  ...    0              0     1.0
102  560160    0       0  ...    0              0     0.0
110  391880    3       1  ...    2              2     0.0
124  393449    1       0  ...    0              0     0.0
126  938115    0       0  ...    0              0     1.0
128  766309    0       1  ...    0              0     1.0
136  851152    1       0  ...    0              1     0.0
138  424820    1       0  ...    0              1     0.0
145  504412    1       1  ...    2              3     1.0
156  150072    0       0  ...    0              0     1.0
159  452356    2       0  ...    0              0     0.0
160  849811    3       0  ...    0              1     0.0

[30 rows x 18 columns]